### ISSUE TITLE
Courses 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#167]
1)Please hide the following for now:
- Course Calendar Tabon the left. 
- The Public dates
- Private Dates
- View Full Schedule

2)Edit the word Day(s) under each course title to be Days.
3) The course objectives should be appearing in the same page for the Course Overview, the content is added but it doesn't show.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/36/issue-167-comments-in-issue-done/diff

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
@LamiaSalah please confirm

**Comment by LamiaSalah** [comment]
@ahmedelbougha 

- The duration of each course is deleted, what I asked for is the duration of units, not courses.
- The format of the learning objectives section is a total mess and needs to be fixed.

**Comment by ahmedelbougha** [comment]
Monday 16/07/2018

**Comment by ahmedelbougha** [comment]
Done, please checking example: http://skillsbuilderpro.com/courses/more/34

**Comment by LamiaSalah** [comment]
There's still an issue with the font and size format Ahmed. When this was added, we ensured they're all with the same font size and color.

**Comment by HeshamHassan** [comment]
Done.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
The font color is fixed, I made it black, but for the font type, size ..etc, you need to fix this on your own from CMS backend.

**Comment by ahmedelbougha** [comment]
Example: http://skillsbuilderpro.com/courses/more/34
@LamiaSalah @HeshamHassan 
Confirm!

**Comment by LamiaSalah** [comment]
Confirmed

**Comment by LamiaSalah** [comment]
Confirm
