### ISSUE TITLE
Arabic Pre-Assessment Editing Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#226]
When we type/insert a big amount of Arabic letters in the question body field, and click on submit, the Arabic contents disappear and when refreshing the page, the whole question disappears.

Ex.: Q3 in the course: SMART STRATEGIES FOR GOING GLOBAL
![image](https://user-images.githubusercontent.com/11155105/49590032-e4387900-f97b-11e8-8ac8-5c7c0a60e719.png)

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha fixed its live now please confirm and close 
http://skillsbuilderpro.com/courses/assessment/questions/33

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha fixed its live now please confirm and close

**Comment by HeshamHassan** [comment]
@mohamedMahdyCc 
> @HeshamHassan @ahmedelbougha fixed its live now please confirm and close
> http://skillsbuilderpro.com/courses/assessment/questions/33

The 3rd question is missing. the English part was entered successfully. When the Arabic part entered with the long text, the whole question disappeared.
Check this URL: http://skillsbuilderpro.com/courses/assessment/question/edit/33/265
Or this: http://skillsbuilderpro.com/courses/assessment/question/edit/33/266

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
You fixed the long Arabic text. Also, you made the text boxes expandable. That's a good thing. But, the text boxes are very big. 
- [x] Let the text box be 1 line hight with the ability to expand.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
Done! and will push live next sunday nchallah

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.

**Comment by LamiaSalah** [comment]
@

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  There's still an issue in the ARabic course Managing Anger, in the pre test question no 7, does not show
