### ISSUE TITLE
SPB-40: [ENHANCEMENT] Create two versions of themes

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#40]
We need to have 2 versions of themes, one for frontend and the other for backend. I know there will be redundancy, but further we will have a new design should be applied.

**Technical Approach**
Create new folder `themes/certigate/modules/backend/`
```
backend
       > categories
       > cms
       > courses
       > default-module
       > issue-tracker
       > notifications
       > organizations
       > system
       > users
```
```
frontend
       > categories
       > cms
       > courses
       > default-module
       > issue-tracker
       > notifications
       > organizations
       > system
       > users
```

## Technical Note 
> before you run `./deploy.sh` you need to drop the database completely and create it again , as the old schema was attached to the entities classes which are all moved to backend modules

**Comment by solimansamy** [comment]
https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/26

**Comment by solimansamy** [comment]
Check routes below for Courses module

**Backend routes**

routes.EvTemplates.options.route = "/courses/ev-templates"
routes.newEvTemplate.options.route = "/courses/ev-templates/new"
routes.editEvTemplate.options.route = "/courses/ev-templates/edit[/:id]"
routes.coursesTrainingMaterials.options.route = "/courses/training-materials"
routes.coursesPending.options.route = "/courses/pending/:id"
routes.coursesApproval.options.route = "/courses/approve/:id"
routes.coursesDisapproval.options.route = "/courses/disapprove/:id"
routes.coursesEdit.options.route = "/courses/edit/:id"
routes.coursesDelete.options.route = "/courses/delete/:id"
routes.resourcesList.options.route = "/courses/resources[/:processResult]"
routes.resourcesListPerCourse.options.route = "/courses/resources/:courseId[/:processResult]"
routes.resourcesNewPerCourse.options.route = "/courses/resources/new/:courseId"
routes.resourcesEdit.options.route = "/courses/resources/edit/:courseId"
routes.resourcesEditPerCourse.options.route = "/courses/resources/edit/:id/:courseId"
routes.resourcesDelete.options.route = "/courses/resources/delete/:id"
routes.resourcesDeletePerCourse.options.route = "/courses/resources/delete/:id/:courseId"
routes.resourcesResourceDownload.options.route = "/courses/resources/download/:id"
routes.courseEvaluations.options.route = "/courses/evaluation[/:courseId]"
routes.newCourseEvaluation.options.route = "/courses/evaluation/new[/:courseId]"
routes.editCourseEvaluation.options.route = "/courses/evaluation/edit[/:courseId]"
routes.courses.options.route = "/courses[/:action]"
routes.examProctors.options.route = "/courses/exam/proctors/:id"
routes.examBooking.options.route = "/courses/exam/book"
routes.examRequests.options.route = "/courses/exam/requests"
routes.acceptRequest.options.route = "/courses/exam/request/accept[/:id]"
routes.declineRequest.options.route = "/courses/exam/request/decline[/:id]"
routes.tvtcaccept.options.route = "/courses/exam/tvtc/accept[/:id[/:token]]"
routes.tvtcdecline.options.route = "/courses/exam/tvtc/decline[/:id[/:token]]"

**Frontend routes**

routes.studentEvaluation.options.route = "/courses/vote/:courseEventId"
routes.courseOutlines.options.route = "/courses/outlines[/:courseId]"
routes.courseOutlinesPdf.options.route = "/courses/outlines/generate-pdf/:id"
routes.coursesInstructorCalendar.options.route = "/courses/instructor-calendar"
routes.coursesInstructorTraining.options.route = "/courses/instructor-training[/:token]"
routes.myCourses.options.route = "/courses/mycourses"
routes.coursesMore.options.route = "/courses/more/:id[/:courseEventId]"
routes.coursesCalendar.options.route = "/courses/calendar[/:token]"
routes.coursesEnroll.options.route = "/courses/enroll/:id"
routes.coursesLeave.options.route = "/courses/leave/:id"

**Comment by badr4php** [comment]
**QA issues**

- [x] 1-when run deploy.sh there is Fatal error: Cannot use CMS\Entity\MenuItemRepository as MenuItemRepository because the name is already in use in /vagrant/module/backend/CMS/src/CMS/Entity/MenuItemRepositoryFactory.php on line 7


- [x] 2 -Exception when create new page or update old one.

- [x] 3- when try to deactivate or activate page its return not found .

- [x] 4- Exception when submit new orgnization.

- [x] 5- Exception when update orgnization

- [ ] 6- when try to activate or deactivate organization it return not found page 

- [x] 7- Exception when create new user 'Route with name "users" not found'

- [x] 8- Exception when update user 'Route with name "users" not found'

- [x] 9- Exception when activate or deactivate  user 'Route with name "users" not found'

- [x] 10- I can't add or update courses  ,page not found.

- [x] 11- backend/course-events return page not found.

- [x] 12 -backend/courses/ev-templates   return page not found

- [x] 13- backend/system/settings  return page not found

- [x] 14- Exception when call  'courses/calendar' 

- [x] 15 - Exception when call backend/users/instructors 

- [x] 16 - Exception when call courses/instructor-training 

- [x] 17- when call  'trans/setlocale/ar_AR' or  'trans/setlocale/en_US'   there is Fatal error: Class 'CMS\Service\Cache\CacheHandler' not found in /var/www/html/module/common/Translation/src/Translation/Controller/IndexController.php on line 21 

- [x] 18- Exception when call 'courses/mycourses'

**Comment by babanesma** [comment]
@badr4php issue #2 is resolved

**Comment by babanesma** [comment]
@badr4php all issues are resolved except : 
issue 1 : I can't replicate it , I ran deploy.sh several times with no problems 
issue 6 : although the not found page issue is resolved this needs another fix to make the deletion work as organization type has been changed and organization can have several type , so it is not related to modules separation

**Comment by badr4php** [comment]
QA issues phase 2

- [x] 1- after create new page its redirect to  "/cms/page",it must be redirect to "backend/cms/page"

- [x] 2- when create roles there is Fatal error: Class 'Backend\Users\Form\RoleForm' not found in /var/www/html/module/backend/Users/src/Users/Controller/RolesController.php on line 57

- [x] 3- when update roles there is Fatal error: Class 'Backend\Users\Form\RoleForm' not found in /var/www/html/module/backend/Users/src/Users/Controller/RolesController.php on line 96

- [x] 4-  Exception when activate or deactivate roles 'Class 'Users\Entity\Role' does not exist'

- [x] 5-when try to activate  categories it return not found page

- [x] 6- when try to create course outlines its return not found page 'backend/courses/outlines/2'

- [x] 7-Exception when edit settings  'Route with name "backednSystemSettings" not found'

- [ ] 8- '/quote' , '/quote/training/private' and '/quote/training/public'  uri  return page not found

- [x] 9- /course-event-subscription/alert-subscribe/1   uri return page not found

- [x] 10- when book exam there is Fatal error: Class 'System\Service\Cache\CacheHandler' not found in /var/www/html/module/frontend/Courses/src/Courses/Model/Exam.php on line 76

- [ ] 11- when deactivate atps organizations -'backend/organizations/atps'  or  atcs organizations 'backend/organizations/atcs'  it return not found page

- [x] 12 - course-events ,deactivate or activate courses return page not found here backend/courses 
![course-events](https://user-images.githubusercontent.com/24792169/34161047-f9aae778-e4d7-11e7-90b1-0d2369f9cdaa.png)

- [ ] 13- GeneralResources menue return page not found  here 
![general-resources](https://user-images.githubusercontent.com/24792169/34161189-8116fcba-e4d8-11e7-8ad3-81400b4d2165.png)

- [x] 14- Class Room Training menu return not found page here 
![quote](https://user-images.githubusercontent.com/24792169/34161258-c863b2d4-e4d8-11e7-8598-0e4415b9ea86.png)

**Comment by badr4php** [comment]
@babanesma   please check last comments

**Comment by babanesma** [comment]
@badr4php phase 2 issues are resolved , please pull and check

**Comment by badr4php** [comment]
issue 8 : Links must be in front end now their found in back end. 
issue 11,12 not solved
- [x] 1- after create course outlines  it redirect to /courses/outlines/{id}  but it must redirect to  /backend/courses/outlines/{id}

- [x] 2- exception when try to edit course outline. 

- [x] 3- in this  http://local-skillsbuilder.com/backend/quote  page please modify 'Public Training' and 'Private Training' links .
![public-training](https://user-images.githubusercontent.com/24792169/34408492-ef8abd76-ebcc-11e7-9261-173e7f81ba14.png)

- [x] 4- in this  http://local-skillsbuilder.com/backend/course-events   page  Create new Course Event ,Activate and  Edit links must be modified .

- [ ] 5- in http://local-skillsbuilder.com/courses/calendar   Public Training' , 'Private Training' and Download links return not found .
