### ISSUE TITLE
SBP-80 : Sign in page issues  

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/skillsbuilder#80]
- [x] Delete please sign in message and make it fit to the screen without scroll

- [x] There are missing pictures and the header has unsuitable animation.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/87

**Comment by ahmedelbougha** [comment]
done

**Comment by Ali-Galal** [comment]
@ahmedelbougha did you upload it to our server? because I see it still not done

**Comment by ahmedelbougha** [comment]
yes I just uploaded them.
